name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Pull the repo so it can save the files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake files
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Adhityae-506
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the generated files to your repo
      - name: Push Snake Files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generated Snake Animation"
          add: "dist/*.svg"
